name: health_mate_app
description: A personal health tracker app for tracking steps, calories, and water intake.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Database
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  
  # Utilities
  intl: ^0.19.0
  
  # Charts
  fl_chart: ^0.66.0
  
  # Notifications
  flutter_local_notifications: ^17.0.0
  
  # Preferences
  shared_preferences: ^2.2.2
  
  # Timezone
  timezone: ^0.9.4
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

